
name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  static-analysis:
    name: "Static Analysis"
    uses: "greg0ire/.github/.github/workflows/phpstan.yml@split-sa-workflow"
    with:
      php-version: "8.1"
